create table School(
   id int primary key generated by default as identity,
   schoolName varchar(50) not null,
   city varchar(20) not null
);

insert into School(schoolName, city) values
('first', 'Moskva'),
('second', 'Piter');

create table Pupil (
    id int primary key generated by default as identity,
    fio varchar(100) not null,
    birthDate varchar(20) not null,
    phoneNumber varchar(20) not null,
    schoolId int references School(id) on delete set null
);

insert into Pupil(fio, birthDate, phoneNumber,schoolId) values
('novikova anastasia borisovna', '1999-08-21', '1234567',1),
('petrova katerina borisovna', '2000-08-05', '5678907',1),
('nikolaev nikolai nokolaevich', '1980-09-21', '89654321',2),
('sidorova anastasia borisovna', '1999-08-21', '1234567',2),
('ponchik katerina borisovna', '2000-08-05', '5678907',1),
('samatov nikolai nokolaevich', '1980-09-21', '89654321',2);






